hub:
  config: 
    Authenticator:
      admin_users:
        - adon55
      allowed_users:
        - adon22
    DummyAuthenticator:
      password: aslkdj1231
    JupyterHub:
      authenticator_class: dummy

  singleuser:
    image:
      name:
    extraVolumeMounts:
      - name: etc-gitconfig
        mountPath: /etc/gitconfig
        subPath: gitconfig
        readOnly: true
      # - name: etc-gitconfig
      #   mountPath: /etc/github/github-app-private-key.pem
      #   subPath: github-app-private-key.pem
      #   readOnly: true
  
  initContainers:
      - name: git-clone-templates
        image: alpine/git
        args:
          - clone
          - --single-branch
          - --branch=master
          - --depth=1
          - --
          - https://github.com/uottawa-infra/eecshub-homepage.git
          - /etc/jupyterhub/custom
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: custom-templates
            mountPath: /etc/jupyterhub/custom
    extraVolumes:
      - name: custom-templates
        emptyDir: {}
    extraVolumeMounts:
      - name: custom-templates
        mountPath: /etc/jupyterhub/custom

    extraConfig:
      templates: |
        c.JupyterHub.template_paths = ['/etc/jupyterhub/custom/jupyterhub/templates']